# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

recorder:
  commit_interval: 30

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

shell_command:
  renew_certificate: "/home/homeassistant/.homeassistant/renew_certificate.sh"
  git_pull_config: "git -C /home/homeassistant/.homeassistant pull"

input_number:
  demand_peak_current_month:
    name: Demand peak current month
    min: 0
    max: 50
    step: 0.01
    unit_of_measurement: kW
    mode: box
  demand_peak_previous_month:
    name: Demand peak previous month
    min: 0
    max: 50
    step: 0.01
    unit_of_measurement: kW
    mode: box
  demand_peak_two_months_ago:
    name: Demand peak two months ago
    min: 0
    max: 50
    step: 0.01
    unit_of_measurement: kW
    mode: box
  demand_tariff_max:
    name: Demand tariff max
    min: 0
    max: 50
    step: 0.01
    unit_of_measurement: kW
    mode: box
  demand_global_max:
    name: Demand global max
    min: 0
    max: 50
    step: 0.01
    unit_of_measurement: kW
    mode: box

homeassistant:
  external_url: https://sveneniris.duckdns.org
  latitude: 50.89233978360891
  longitude: 4.751319141342004

lovelace:
  dashboards:
    dashboard-test:
      mode: yaml
      title: Verbruik
      icon: mdi:home-lightning-bolt-outline
      show_in_sidebar: true
      require_admin: false
      filename: dashboard_test.yaml
    admin:
      mode: yaml
      title: Beheer
      icon: mdi:shield-cog-outline
      show_in_sidebar: true
      require_admin: true
      filename: admin.yaml

# duckdns:
#   domain: sveneniris
#   access_token: 0e26191e-5e43-4beb-8024-9fde88c1d9d1

http:
  # For extra security set this to only accept connections on localhost if NGINX is on the same machine
  # Uncommenting this will mean that you can only reach Home Assistant using the proxy, not directly via IP from other clients.
  # server_host: 127.0.0.1
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
  trusted_proxies: 127.0.0.1
# http:
#   ssl_certificate: /etc/letsencrypt/live/sveneniris.duckdns.org/fullchain.pem
#   ssl_key: /etc/letsencrypt/live/sveneniris.duckdns.org/privkey.pem

template:
  - sensor:
      - name: "Battery Power In"
        unique_id: battery_power_in
        unit_of_measurement: "kW"
        device_class: power
        state_class: measurement
        state: >
          {% set power = states('sensor.battery_power')|float(0) / 1000 %}
          {% if power < 0 %}
            {{ power|abs }}
          {% else %}
            0
          {% endif %}

      - name: "Battery Power Out"
        unit_of_measurement: "kW"
        unique_id: battery_power_out
        device_class: power
        state_class: measurement
        state: >
          {% set power = states('sensor.battery_power')|float(0) / 1000 %}
          {% if power >= 0 %}
            {{ power }}
          {% else %}
            0
          {% endif %}

      - name: "Grid Power In"
        unique_id: grid_power_in
        unit_of_measurement: "kW"
        device_class: power
        state_class: measurement
        state: >
          {% set power = states('sensor.filtered_grid_power')|float(0) / 1000 %}
          {% if power < 0 %}
            0
          {% else %}
            0
          {% endif %}

      - name: "Grid Power Out"
        unique_id: grid_power_out
        unit_of_measurement: "kW"
        device_class: power
        state_class: measurement
        state: >
          {% set power = states('sensor.filtered_grid_power')|float(0) / 1000 %}
          {% if power >= 0 %}
            0
          {% else %}
            0
          {% endif %}

      - name: "Three Month Peak Demand"
        unique_id: three_month_peak_demand
        unit_of_measurement: "kW"
        device_class: power
        state_class: measurement
        state: >-
          {{ [
            states('input_number.demand_peak_current_month') | float(0),
            states('input_number.demand_peak_previous_month') | float(0),
            states('input_number.demand_peak_two_months_ago') | float(0)
          ] | max }}

      - name: "Demand peak current month"
        unique_id: demand_peak_current_month_sensor
        default_entity_id: sensor.demand_peak_current_month
        unit_of_measurement: "kW"
        device_class: power
        state_class: measurement
        state: "{{ states('input_number.demand_peak_current_month') | float(0) }}"

      - name: "Demand peak previous month"
        unique_id: demand_peak_previous_month_sensor
        default_entity_id: sensor.demand_peak_previous_month
        unit_of_measurement: "kW"
        device_class: power
        state_class: measurement
        state: "{{ states('input_number.demand_peak_previous_month') | float(0) }}"

      - name: "Demand peak two months ago"
        unique_id: demand_peak_two_months_ago_sensor
        default_entity_id: sensor.demand_peak_two_months_ago
        unit_of_measurement: "kW"
        device_class: power
        state_class: measurement
        state: "{{ states('input_number.demand_peak_two_months_ago') | float(0) }}"

      - name: "Demand tariff max"
        unique_id: demand_tariff_max
        default_entity_id: sensor.demand_tariff_max
        unit_of_measurement: "kW"
        device_class: power
        state_class: measurement
        state: >-
          {{ [
            2.5,
            states('input_number.demand_peak_previous_month') | float(0),
            states('input_number.demand_peak_two_months_ago') | float(0)
          ] | max }}

      - name: "Demand global max"
        unique_id: demand_global_max
        default_entity_id: sensor.demand_global_max
        unit_of_measurement: "kW"
        device_class: power
        state_class: measurement
        state: >-
          {{ [
            2.5,
            states('input_number.demand_peak_current_month') | float(0),
            states('input_number.demand_peak_previous_month') | float(0),
            states('input_number.demand_peak_two_months_ago') | float(0)
          ] | max }}

sensor:
  - platform: filter
    name: "filtered grid_power"
    unique_id: filtered_grid_power
    entity_id: sensor.on_grid_export_power
    filters:
      - filter: time_simple_moving_average
        window_size: "00:01"
        precision: 2

  - platform: statistics
    name: "Average demand last hour"
    entity_id: sensor.current_average_demand
    state_characteristic: mean
    max_age:
      hours: 1

  - platform: statistics
    name: "Average demand last 24 hours"
    entity_id: sensor.current_average_demand
    state_characteristic: mean
    max_age:
      hours: 24

  - platform: statistics
    name: "Average demand last 7 days"
    entity_id: sensor.current_average_demand
    state_characteristic: mean
    max_age:
      days: 7

  - name: "Solar Power [kWh]"
    platform: integration
    source: sensor.pv_power
    round: 2
    method: left

  - name: "Battery In [kWh]"
    platform: integration
    source: sensor.battery_power_in
    round: 2
    method: left

  - name: "Battery Out [kWh]"
    platform: integration
    source: sensor.battery_power_out
    round: 2
    method: left

  - name: "In-house consumption [kWh]"
    platform: integration
    source: sensor.house_consumption
    round: 2
    method: left

  - name: "Sell [kWh]"
    platform: integration
    source: sensor.grid_power_out
    round: 2
    method: left

  - name: "Buy [kWh]"
    platform: integration
    source: sensor.grid_power_in
    round: 2
    method: left



